server.port: 8081

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root
    password: password-1

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: JKLOXA1DK2P33FZJJDSA
  secretKey: /QMRlR7kxqWKdXalQBxlof4ME6uBERAtfKBvPNEg
  bucketName: moviefun

security:
    basic:
        enabled: false
