spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: JKLOXA1DK2P33FZJJDSA
  secretKey: /QMRlR7kxqWKdXalQBxlof4ME6uBERAtfKBvPNEg
  bucketName: moviefun

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies

security:
  basic:
    enabled: false
