spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/struts?useSSL=false
    username: root
    password: password-1

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
